import Banner from "@/components/studio/Banner";
import Header from "@/components/studio/Header";
import "@/app/globals.css";
import Footer from "@/components/studio/Footer";
import Navbar from "@/components/studio/Navbar";

export const metadata = {
  title: "GLad Blog",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="max-w-7xl mx-auto">
      <Navbar />
        <Header />
        <Banner />
        {children}
        <Footer />
      </body>
    </html>
  );
}
